name: Clippy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup component add clippy rustfmt
    - name: Build
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo fmt -- --check 
